### ISSUE TITLE
Can't find some eval jsonl data in MMEB-V2

### ISSUE THREAD

**Issue by zzlinux** [TIGER-AI-Lab/VLM2Vec#93]
Hi, thank you for your excellent work and contribution to the MMEB-V2 leaderboard. 

When I tried to evaluate my model on this benchmark, I found that the three jsonl files used for the video tasks in your code are not provided in [MMEB-V2](https://huggingface.co/datasets/TIGER-Lab/MMEB-V2),  which prevents me from obtaining complete results for comparison with yours. Could you please upload these three files to Hugging Face [MMEB-V2](https://huggingface.co/datasets/TIGER-Lab/MMEB-V2)? Thank you very much. 

Here are the names of the three missing files:
```
video-tasks/data/charades_sta.jsonl
video-tasks/data/momentseeker.jsonl
video-tasks/data/activitynetqa.jsonl
```

And here are the evaluation tasks in which they are respectively used:
```
Charades-STA:
    dataset_parser: moment_retrieval
    dataset_name: Charades-STA
    data_path: video-tasks/data/charades_sta.jsonl
    video_root: None
    clip_root: None
    frame_root: video-tasks/frames/video_mret/charades_sta_frames
    num_negative_clips: 9
    max_video_frames_saved: 64
    max_clip_frames_saved: 8
    num_video_frames: 8
    num_clip_frames: 8
    eval_type: local
MomentSeeker:
    dataset_parser: momentseeker
    dataset_name: MomentSeeker
    data_path: video-tasks/data/momentseeker.jsonl
    video_root: None
    clip_root: None
    raw_dataset_abspath: None
    frame_root: video-tasks/frames/video_mret/momentseeker
    num_negative_clips: 9
    num_video_frames: 8
    eval_type: local
ActivityNetQA:
    dataset_parser: activitynetqa
    dataset_name: ActivityNetQA
    data_path: video-tasks/data/activitynetqa.jsonl
    video_root: video-tasks/videos/video_qa/ActivityNetQA
    frame_root: video-tasks/frames/video_qa/ActivityNetQA
    max_frames_saved: 64
    num_frames: 8
    eval_type: local
```
